### PR TITLE
Ready for review (gh-pages)

### PR DESCRIPTION
**Pull request by BrittanyBlake**
## Project Using Bootstrap: Newsweek clone

-Added a navbar 
-Added different articles
-Added footer
-Added different layouts for different screen sizes
-Styled majority of the project using bootstrap 

[Live Version](https://brittanyblake.github.io/newsweek-clone/)

### CODE REVIEW

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**HI @BrittanyBlake, good work on this project:clap:. Some changes are however required :fast_forward:**

1. Ensure that the logo background color is not different from the header background color. You can use a color picker to identify the exact colors on the page.

2. The original page has a left and right margin. Adjust your page accordingly.

3. On scroll, do not keep the header fixed unless you switch to the mini-version.

4. In the **More Stories** and **Latest News** sections, the margin between text and images is too much.

5. **In the magazine** section: Images should have the same height and the margin between rows should be smaller than you have it. Compare with the original.

6. Your **Featured Slideshow** title is not properly aligned. It should be centered.
image

7. In the section below, and all similar sections, the margin between columns and between article images & text is not properly sized. Please compare with the original.

image

8. Check the left alignments of elements in the footer and adjust to look like the original.

**Yours:**
image

**Original:**
image

9. On medium screens, check the margin between article image and text in **The Debate** section.

10. On medium screen, the section below, just before the **In the magazine** section should be properly sized and centered. Compare with the original.

image

11. On medium screen, the left and right margin and margin between columns should be properly sized.

image

12. The **SUBSCRIBE** section is not properly aligned on medium screens.

13. On small screen sizes, all articles should take full width and be properly aligned as they are in the original page.

14. Check the alignment of social media icons in the footer on small screens. Compare with the original.

15. You are expected to add bootstrap to your project using the Bootstrap CDN as described [here](https://getbootstrap.com/docs/4.3/getting-started/introduction/#css)



_**Kindly make these changes and submit another code review request.**_

**Any question? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

**Comment by BrittanyBlake** [comment]
## Project Using Bootstrap: Newsweek clone

-Fixed color of the navbar. 
-Unfixed the navbar when scrolling.
-Adjusted margins between text and images in various sections on various screen sizes. 
-Adjusted images in the magazine section to ensure they are all the same height. 
 -Aligned featured slideshow title.
-Adjusted the article sizes on small screens.
-Adjusted social media icons on small screens.
-Removed downloaded bootstrap and added it via the CDN link.
-Adjusted alignment of items in the footer. 
-Adjusted subscribe section on the medium screen. 

[Live Version](https://brittanyblake.github.io/newsweek-clone/)

Hopefully this is good to go now!

**Comment by thsvr** [comment]
Project under review by Thaís Vieira

**Comment by thsvr** [comment]
### **Status: CHANGES REQUIRED** :desktop_computer: :computer_mouse: 

Hi @BrittanyBlake , your page looks beautiful and you are almost there. There are few changes required, so please read it carefully:

- as requested on 3, you have to keep a small version of navbar after the scroll. Look at the difference between the original and your version, and please adjust it:

### **Original:**

news-navbar

### **Your version:**

student-version

- as requested on 10 of the list above you have to adjust the images on the medium screen. Please take a look at the following images: 

### **Original:**

original2


### **Your version:**

student-version



- as requested on 12: the subscribe section, on the medium screen, the content has to be centered. Please fix it;





**_Please do these few changes listed above and then submit them for another review._** 

If you have any questions, don't hesitate to contact me through slack [@Thaís Vieira Azevedo](url)

### **Keep doing this amazing work :computer:  and good luck on the next review  :desktop_computer:   ** 

Thaís Vieira (TSE)

**Comment by BrittanyBlake** [comment]
## Project Using Bootstrap: Newsweek clone

-Fixed small version of navbar when scrolling.
-Adjusted images in smaller screens.
-Centered content in the subscribe section on smaller screens.

[Live Version](https://brittanyblake.github.io/newsweek-clone/)

Hopefully this is good to go now!

**Comment by davidmrtz-dev** [comment]
### **Status: Changes required.** 🔍 ♻️ 
****
### Hi @BrittanyBlake . 😄 
### Very good job so far.
### However, the following issues need to be fixed before moving on  👨‍💻  ⬇️ 

****

- [ ] Culture and travel section.
On 'sm' size the images and text must use the 100% width of the container box.
Please fix it.
How it looks now. ⬇️ 

Screen Shot 2020-03-07 at 8 25 45 PM


The example on which the project is based. ⬇️ 

Screen Shot 2020-03-07 at 8 26 50 PM

- [ ] More stories section.
On the same size ('sm') there's an issue on the images of the more stories.
Please fix it so that it looks as much as possible to the example on which the project is based
How it looks now. ⬇️ 

Screen Shot 2020-03-07 at 8 30 11 PM


The example on which the project is based. ⬇️ 

Screen Shot 2020-03-07 at 8 30 27 PM


****

- [ ] Images on sections.
There's are a couple of sections on 'sm' size devices where the images don't use 100% of the width as is required in the example on which the project is based.

How it looks now. ⬇️ 

Screen Shot 2020-03-07 at 8 36 05 PM


The example on which the project is based. ⬇️ 

Screen Shot 2020-03-07 at 8 36 15 PM


****

### **Please kindly make the changes required and submit a new code review once you are ready!** 🙏 

Happy coding! 😄 💻  
If you have any questions or need help, you can message me on slack (@ David Eli Martinez Garcia).

**[TSE:  David Elí]** 👨‍💻 
Github: [@davitomix](https://github.com/davitomix)
Twitter: [@davitomix](https://twitter.com/davitomix007)
Linkedin: [David Elí Martínez García](https://www.linkedin.com/in/davideligarcia/)

**Comment by BrittanyBlake** [comment]
## Project Using Bootstrap: Newsweek clone

-Adjusted images in culture and travel section on the small screen sizes.
-Adjusted spacing between the text and images in more stories and similar sections.
-Adjusted images to take 100% of the screen on small screen sizes.

[Live Version](https://brittanyblake.github.io/newsweek-clone/)

Ok, hopefully this is finally all fixed now!

**Comment by lekegitrepo** [comment]
Yeah, this definitely fix all.

**Comment by lekegitrepo** [comment]
## @BrittanyBlake 👏 💯 
### Excellent job. This project is approved.
### Good luck with the next project.

### Reviewed by: _Temitayo Adeleke_

-   Github: [@lekegitrepo](https://github.com/lekegitrepo)
-   Twitter: [@leketemi](https://twitter.com/leketemi)
-   Linkedin: [linkedin](https://www.linkedin.com/in/adeleke-temitayo-a69125188/)

**Review by lekegitrepo — APPROVED** [review]
## Status: Approved.

**Comment by BrittanyBlake** [comment]
Thank you!!

**Pull request merged**
